spring:
  datasource:
    druid:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mywarehouse?characterEncoding=utf8&useSSL=true&serverTimezone=UTC&useSSL=false
      username: root
      password: 123456
      max-active: 20
      max-wait: 5000
      initial-size: 1
      filters: stat,log4j,wall
      validation-query: SELECT 'X'
      enable: true

      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: 1700502162
        url-pattern: /druid/*
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB


  thymeleaf:
    cache: false
    enabled: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


shiro:
  hash-algorithm-name: md5
  hash-iterations: 2
  anon-urls:
   - /index.html*
   - /sys/toLogin*
   - /login/login*
   - /login/getCode
   - /resources/**
   - /
  login-url: /index.html
  log-out-url: /login/logout*
  authc-ulrs:
   - /**

server:
  port: 8080